name: places_service
description: A service that makes it easy to get information from the Places Api
version: 0.1.5
homepage: https://filledstacks.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # data models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  geolocator: ^11.0.0
  google_maps_webservice_ex: ^0.0.1+2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  # data models
  freezed: ^2.5.0
  json_serializable: ^6.7.1

flutter:
