name: places_service
description: A service that makes it easy to get information from the Places Api
version: 0.1.5
homepage: https://filledstacks.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # data models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  geolocator: ^11.0.0
  google_maps_apis: ^1.0.1+1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  # data models
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
